CREATE TABLE `GuestList` (
	`UserID` INT NOT NULL AUTO_INCREMENT,
	`FirstName` VARCHAR(15) NOT NULL,
	`LastName` VARCHAR(20) NOT NULL,
	`Email` VARCHAR(30) NOT NULL,
    'Rsvp' BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (`UserID`)
);